name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Main Test
      id: main-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Main Test
        setup-command: npm install
        command: HOME=. npx pm2 start npm -- start && CI=true npm test && HOME=. npx
          pm2 delete 0
        timeout: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAIN-TEST_RESULTS: "${{steps.main-test.outputs.result}}"
      with:
        runners: main-test
